### ISSUE TITLE
Authentication Error Help!

### ISSUE THREAD

**Issue by Mobility-Inc-Marq** [binary1230/wellsfargo-bulk-PDF-statement-downloader#12]
![Screenshot_2024-04-03-00-06-30-591.jpg](https://github.com/binary1230/wellsfargo-bulk-PDF-statement-downloader/assets/151239242/ca9164e4-0d1e-4c63-8193-1c89948a50af)

**Comment by binary1230** [comment]
I'm not sure what you're trying to do,

This script almost certainly won't work on a mobile phone, please try the instructions again but on a desktop pc

**Comment by binary1230** [comment]
Super suspicious likely bot account. I'm going to report it
